const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules/playwright-core');
const base='http://127.0.0.1:3000';const products=JSON.parse(fs.readFileSync('/private/tmp/eshwe-browser-fixture.json'));const result=[];
async function record(name,fn){try{await fn();result.push({name,status:'passed'});console.log('PASS',name);}catch(error){result.push({name,status:'failed',error:error.message});throw error;}}
async function login(page,phone){await page.goto(`${base}/app/account/`);await page.getByRole('button',{name:'CONTINUE WITH SMS'}).click();await page.getByPlaceholder('9876543210').fill(phone);await page.getByRole('button',{name:'PROCEED',exact:true}).click();await page.getByPlaceholder('6-digit code').fill('123456');await page.getByRole('button',{name:'VERIFY',exact:true}).click();await page.getByRole('button',{name:'SIGN OUT',exact:true}).waitFor();}
async function main(){
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 try{
 const alice=await browser.newContext({viewport:{width:390,height:844}});const bob=await browser.newContext({viewport:{width:1440,height:1000}});const errors=[];const badPayloads=[];
 for(const context of [alice,bob]){await context.addInitScript(()=>{window.__paymentOptions=null;window.Razorpay=class{constructor(options){this.options=options;}on(){}open(){window.__paymentOptions=this.options;}};});context.on('page',page=>{page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(new URL(r.url()).pathname.endsWith('.txt')&&r.status()!==200)badPayloads.push(r.url());});});}
 const app=await alice.newPage();const web=await bob.newPage();
 await record('PWA login loads the address selected on the web',async()=>{await login(app,'9999999991');await app.getByText('Office test street',{exact:true}).waitFor();assert.equal(await app.getByLabel('Saved delivery address').inputValue(),'office');});
 await record('PWA selected-address change synchronizes to another tab',async()=>{const tab=await alice.newPage();await tab.goto(`${base}/app/account/`);await app.getByLabel('Saved delivery address').selectOption('home');await tab.waitForFunction(()=>document.querySelector('select[aria-label="Saved delivery address"]')?.value==='home');await app.getByLabel('Saved delivery address').selectOption('office');await tab.close();});
 await record('Guest cart changes synchronize across tabs and login does not double quantity',async()=>{const guest=await browser.newContext();const a=await guest.newPage();const b=await guest.newPage();await a.goto(`${base}/app/product/?slug=${products[1].slug}`);await b.goto(`${base}/app/checkout/`);await a.getByRole('button',{name:'ADD TO CART',exact:true}).last().click();await b.getByText(products[1].name,{exact:true}).first().waitFor();await login(a,'9999999992');await a.goto(`${base}/app/checkout/`);await a.getByText(products[1].name,{exact:true}).first().waitFor();assert.equal(await a.getByRole('button',{name:'Decrease quantity'}).first().locator('..').locator('span').innerText(),'1');await guest.close();});
 await record('Last available piece is shown live to another web customer',async()=>{await web.goto(`${base}/product/${products[0].slug}/`);await web.getByText('Only 1 left in stock',{exact:false}).first().waitFor();await app.goto(`${base}/app/product/?slug=${products[0].slug}`);await app.getByRole('button',{name:'ADD TO CART',exact:true}).last().click();await app.locator('.mobile-app-action-bar').getByRole('button',{name:'Decrease quantity'}).waitFor();await app.goto(`${base}/app/checkout/`);await app.getByRole('button',{name:'CHECKOUT',exact:true}).click();await app.getByRole('button',{name:'CONFIRM ADDRESS AND PROCEED',exact:true}).click();await app.getByRole('button',{name:'PAY NOW',exact:true}).click();await app.waitForFunction(()=>Boolean(window.__paymentOptions));await web.getByText('TEMPORARILY RESERVED',{exact:true}).first().waitFor();assert.ok((await web.locator('body').innerText()).includes('Temporarily reserved'));});
 let orderId;
 await record('Interrupted checkout can be recovered without creating a second payment',async()=>{const payment=await app.evaluate(()=>({id:window.__paymentOptions.order_id,amount:window.__paymentOptions.amount}));assert.equal(payment.amount,10000);await app.reload();await app.getByRole('link',{name:'You have a checkout in progress. Resume or check payment'}).click();await app.getByRole('button',{name:'Resume payment'}).waitFor();orderId=new URL(app.url()).searchParams.get('order');await app.getByRole('button',{name:'Resume payment'}).click();await app.waitForFunction(()=>Boolean(window.__paymentOptions));assert.equal(await app.evaluate(()=>window.__paymentOptions.order_id),payment.id);});
 await record('Payment confirmation uses server amount and removes purchased cart once',async()=>{await app.evaluate(async()=>{const response=await fetch('/__test/payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId:window.__paymentOptions.order_id})});await window.__paymentOptions.handler(await response.json());});await app.getByText('Paid',{exact:true}).waitFor();await app.getByText('Total: ₹100.00',{exact:true}).waitFor();await web.getByText('OUT OF STOCK',{exact:true}).first().waitFor();await app.reload();await app.getByText('Paid',{exact:true}).waitFor();const tab=await alice.newPage();await tab.goto(`${base}/checkout/`);await tab.getByText(/cart is empty/i).first().waitFor();await tab.close();});
 await record('Receipt storage and account switching do not expose previous customer order',async()=>{const values=await app.evaluate(()=>({local:{...localStorage},session:{...sessionStorage}}));assert.equal(values.session['eshwe.latestOrderConfirmation'],undefined);assert.ok(!JSON.stringify(values).includes('Office test street'));await app.goto(`${base}/app/account/`);await app.getByRole('button',{name:'SIGN OUT',exact:true}).click();await app.getByRole('button',{name:'CONFIRM',exact:true}).click();await app.getByRole('button',{name:'CONTINUE WITH SMS'}).waitFor();await login(app,'9999999992');await app.goto(`${base}/app/order-confirmation/?order=${orderId}`);await app.getByText('Order not found.',{exact:true}).waitFor();assert.ok(!(await app.locator('body').innerText()).includes('Alice Test'));});
 await record('Static product metadata, sitemap and navigation payloads are present',async()=>{const response=await web.goto(`${base}/product/${products[0].slug}/`);assert.equal(response.status(),200);assert.equal(await web.locator('link[rel="canonical"]').getAttribute('href'),`https://eshwe.com/product/${products[0].slug}/`);assert.ok((await web.title()).includes(products[0].name));const sitemap=await (await web.request.get(`${base}/sitemap.xml`)).text();assert.ok(sitemap.includes(`/product/${products[0].slug}/`));assert.equal((await web.request.get(`${base}/app/account/index.txt`)).status(),200);assert.equal(badPayloads.length,0);});
 await record('PWA offline navigation shows reconnect screen and does not cache customer pages',async()=>{await app.goto(`${base}/app/account/`);await app.evaluate(()=>navigator.serviceWorker.ready);await app.waitForFunction(()=>Boolean(navigator.serviceWorker.controller));await alice.setOffline(true);await app.goto(`${base}/app/orders/`);await app.getByText(/offline/i).first().waitFor();assert.ok(!(await app.locator('body').innerText()).includes('Alice Test'));await alice.setOffline(false);await app.getByRole('heading',{name:'Orders',exact:true}).waitFor();const urls=await app.evaluate(async()=>{const all=[];for(const key of await caches.keys())for(const req of await (await caches.open(key)).keys())all.push(new URL(req.url).pathname);return all;});assert.ok(!urls.some(url=>!url.startsWith("/_next/static/")&&/\/(account|orders|checkout|payment|order-confirmation)\//.test(url)));});
 assert.deepEqual(errors,[]);console.log('PASS no browser runtime errors');result.push({name:'No browser runtime errors',status:'passed'});
 }finally{await browser.close();fs.mkdirSync('docs/audits/launch-2026-09-12',{recursive:true});fs.writeFileSync(`${process.env.ESHWE_UI_RESULTS_DIR || 'docs/audits/launch-2026-09-12'}/fix-browser-results.json`,JSON.stringify({testedAt:new Date().toISOString(),environment:'Local static build, Auth/Firestore emulators, simulated OTP and Razorpay',results:result},null,2));}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
