const test=require('node:test');const assert=require('node:assert/strict');const {memoryFirestore}=require('./helpers/firestore.cjs');const {loadBackend,request}=require('./helpers/backend.cjs');
test('incorrect OTP attempts commit before error; fifth attempt locks even the correct code',async()=>{const f=memoryFirestore();const api=loadBackend(f.db).testOnly;const phone='919999999999';const ref=f.db.collection('customerOtpCodes').doc(api.hashValue(phone));await ref.set({codeHash:api.hashVerificationCode(phone,'123456'),expiresAt:Date.now()+60000,attemptCount:0});for(let i=1;i<=5;i++){await assert.rejects(api.verifyStoredCustomerCode(phone,'000000'),e=>e.status===(i===5?429:400));assert.equal((await ref.get()).data().attemptCount,i);}await assert.rejects(api.verifyStoredCustomerCode(phone,'123456'),e=>e.status===429);});
test('valid OTP is consumed once; expired OTP deletion commits',async()=>{const f=memoryFirestore();const api=loadBackend(f.db).testOnly;const phone='919999999999';const ref=f.db.collection('customerOtpCodes').doc(api.hashValue(phone));await ref.set({codeHash:api.hashVerificationCode(phone,'123456'),expiresAt:Date.now()+60000});const results=await Promise.allSettled([api.verifyStoredCustomerCode(phone,'123456'),api.verifyStoredCustomerCode(phone,'123456')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);await ref.set({codeHash:'expired',expiresAt:1});await assert.rejects(api.verifyStoredCustomerCode(phone,'123456'));assert.equal((await ref.get()).exists,false);});
test('forged payment signature cannot mutate a paid or pending order',async()=>{const f=memoryFirestore({'checkoutOrders/A':{razorpayOrderId:'gateway',paymentStatus:'captured'}});const api=loadBackend(f.db).testOnly;await assert.rejects(api.verifyPaymentForOrder({internalOrderId:'A',razorpayOrderId:'gateway',razorpayPaymentId:'pay',razorpaySignature:'fake'}));assert.equal(f.records.get('checkoutOrders/A').paymentStatus,'captured');});
test('checkout and owner APIs reject unauthenticated/non-owner access and cross-account order reads',async()=>{const f=memoryFirestore({'checkoutOrders/A':{userId:'bob'}});const api=loadBackend(f.db,{users:{alice:{uid:'alice'},fakeOwner:{uid:'x',email:'ajyghosh@gmail.com',email_verified:false}}});assert.equal((await request(api.checkoutStatus,{internalOrderId:'A'})).status,401);assert.equal((await request(api.checkoutStatus,{internalOrderId:'A'},'alice')).status,404);assert.equal((await request(api.ownerProductAction,{},'alice')).status,403);assert.equal((await request(api.ownerOrderAction,{},'fakeOwner')).status,403);});

test('old signed webhook event reconciles current provider capture and never downgrades payment',async()=>{
 const payment={id:'pay',order_id:'gateway',amount:100,currency:'INR',status:'captured'};
 const f=memoryFirestore({'sarees/P':{sku:'P',price:1,status:'active',availableStock:0,reservedStock:1},'checkoutOrders/A':{userId:'alice',razorpayOrderId:'gateway',amountPaise:100,currency:'INR',cartItems:[{productId:'P',sku:'P',quantity:1}],reservationState:'held',reservationExpiresAt:Date.now()+60000,paymentStatus:'pending'}});
 class Gateway{constructor(){this.payments={fetch:async()=>payment};this.orders={fetchPayments:async()=>({items:[payment]})};}}
 const api=loadBackend(f.db,{mocks:{razorpay:Gateway}});await api.testOnly.handleWebhookEvent({event:'payment.failed',payload:{payment:{entity:{id:'pay',order_id:'gateway',notes:{internalOrderId:'A'}}}}});assert.equal(f.records.get('checkoutOrders/A').paymentStatus,'captured');assert.equal(f.records.get('sarees/P').reservedStock,0);await api.testOnly.handleWebhookEvent({event:'payment.authorized',payload:{payment:{entity:{id:'pay',order_id:'gateway'}}}});assert.equal(f.records.get('sarees/P').availableStock,0);
 const rejected=await request(api.razorpayWebhook,{event:'payment.failed'});assert.equal(rejected.status,400);assert.equal(f.records.get('checkoutOrders/A').paymentStatus,'captured');
});
